create database yesorno;

create table member_grade_cd(
	MEMBER_GRADE_ID			INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_GRADE_LEVEL		INT	UNIQUE,
    MEMBER_GRADE_NAME		VARCHAR(32) UNIQUE
);

insert into member_grade_cd values(0, 0, "Admin");
insert into member_grade_cd values(0, 1, "SubAdmin");
insert into member_grade_cd values(0, 10, "Normal");
insert into member_grade_cd values(0, 100, "Retired");

create table members_tb(
	MEMBER_ID 				INT PRIMARY KEY AUTO_INCREMENT,
    MEMBER_GRADE_ID			INT NOT NULL,
    MEMBER_EMAIL			VARCHAR(128) UNIQUE NOT NULL,
    MEMBER_NICKNAME			VARCHAR(16) UNIQUE NOT NULL,
    MEMBER_JOIN_DATE		DATETIME NOT NULL,
    MEMBER_TOKEN			VARCHAR(300),
    FOREIGN KEY (MEMBER_GRADE_ID) REFERENCES member_grade_cd(MEMBER_GRADE_ID) ON DELETE RESTRICT
);

create table vote_boards_tb(
	VOTE_BOARD_ID			INT PRIMARY KEY AUTO_INCREMENT,
	WRITER_MEMBER_ID		INT NOT NULL,
    VOTE_BOARD_WRITTEN_DATE	DATETIME NOT NULL,
    VOTE_BOARD_VIEW_CNT		INT NOT NULL,
    VOTE_BOARD_TITLE		VARCHAR(64) NOT NULL,
    VOTE_BOARD_CONTENT		VARCHAR(256) NOT NULL,
    VOTE_BOARD_IMAGE_URL	VARCHAR(128),
    VOTE_END_DATE			DATETIME NOT NULL,
    VOTE_END_CNT			INT,
    FOREIGN KEY (WRITER_MEMBER_ID) REFERENCES members_tb(MEMBER_ID) ON DELETE RESTRICT
);

create table vote_progresses_tb(
	VOTE_PROGRESS_ID		INT PRIMARY KEY AUTO_INCREMENT,
    VOTE_BOARD_ID			INT NOT NULL,
    VOTER_MEMBER_ID			INT NOT NULL,
    VOTE_AGREE_DISGREE		BOOLEAN NOT NULL,
    VOTE_DATE				DATETIME NOT NULL,
    FOREIGN KEY (VOTE_BOARD_ID) REFERENCES vote_boards_tb(VOTE_BOARD_ID) ON DELETE CASCADE,
    FOREIGN KEY (VOTER_MEMBER_ID) REFERENCES members_tb(MEMBER_ID) ON DELETE RESTRICT
);

create table comments_tb(
	COMMENT_ID					INT PRIMARY KEY AUTO_INCREMENT,
    COMMENT_OWNED_BOARD_ID		INT NOT NULL,
    COMMENT_WRITER_MEMBER_ID	INT	NOT NULL,
    COMMENT_WRITTEN_DATE		DATETIME NOT NULL,
    COMMENT_CONTENT				VARCHAR(256) NOT NULL,
    COMMENT_BASE_CNT			INT NOT NULL,
    COMMENT_STEP_CNT			INT NOT NULL,
    FOREIGN KEY (COMMENT_OWNED_BOARD_ID) REFERENCES vote_boards_tb(VOTE_BOARD_ID) ON DELETE CASCADE,
    FOREIGN KEY (COMMENT_WRITER_MEMBER_ID) REFERENCES members_tb(MEMBER_ID) ON DELETE RESTRICT
);