@echo off

SETLOCAL

SET JAR_NAME=Client.jar

SET RECORD_FILE_PATH=res/1)송신파일_35350081.180404104958
SET OUTPUT_FILE_PATH=res/output/1)송신파일_35350081.180404104958.rpy
SET ATTRIBUTE_CONFIG_FILE_PATH=res/config/attrConfig.txt

SET FB_IP=127.0.0.1
SET FB_PORT=9999

SET FB_PARENT_BANK_CODE_3=039
SET FB_PARENT_COMP_CODE=7770011
SET FB_PARENT_ACCOUNT_NUMB=86088800173
SET FB_REQ_FILE=35350081.180404104958
SET FB_MSG_NUMB_S=0
SET FB_PARENT_COMP_NAME=ＡＮＰ물품대금　　　

SET REUSABLE_SOCKET_MODE=FALSE
SET SOCKET_CNT=2
SET SOCKET_THREAD_TIMEOUT=10000
SET RECORD_RESEND_MAX_TRY=5
SET RECORD_RESEND_DELAY=5000
SET RECORD_TGT_SEND_PER_SEC=15

SET LOG_LEVEL=SERVICE

cls

java -jar %JAR_NAME% ^
 %RECORD_FILE_PATH% ^
 %OUTPUT_FILE_PATH% ^
 %ATTRIBUTE_CONFIG_FILE_PATH% ^
 %FB_IP% %FB_PORT% ^
 %FB_PARENT_BANK_CODE_3% ^
 %FB_PARENT_COMP_CODE% ^
 %FB_PARENT_ACCOUNT_NUMB% ^
 %FB_REQ_FILE% ^
 %FB_MSG_NUMB_S% ^
 %FB_PARENT_COMP_NAME% ^
 %REUSABLE_SOCKET_MODE% ^
 %SOCKET_CNT% ^
 %SOCKET_THREAD_TIMEOUT% ^
 %RECORD_RESEND_MAX_TRY% ^
 %RECORD_RESEND_DELAY% ^
 %RECORD_TGT_SEND_PER_SEC% ^
 %LOG_LEVEL% 

cd res\output

start.

cd ..
cd ..

ENDLOCAL